# Form implementation generated from reading ui file 'ticket_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.titleLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(310, 0, 131, 31))
        self.titleLabel.setObjectName("titleLabel")
        self.ticketIdLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.ticketIdLabel.setGeometry(QtCore.QRect(40, 70, 47, 13))
        self.ticketIdLabel.setObjectName("ticketIdLabel")
        self.ticketIdInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ticketIdInput.setGeometry(QtCore.QRect(90, 70, 113, 20))
        self.ticketIdInput.setObjectName("ticketIdInput")
        self.userNameInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.userNameInput.setGeometry(QtCore.QRect(90, 100, 113, 20))
        self.userNameInput.setObjectName("userNameInput")
        self.userNameLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.userNameLabel.setGeometry(QtCore.QRect(30, 100, 61, 16))
        self.userNameLabel.setObjectName("userNameLabel")
        self.priorityLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.priorityLabel.setGeometry(QtCore.QRect(30, 130, 47, 13))
        self.priorityLabel.setObjectName("priorityLabel")
        self.priorityLowRadio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.priorityLowRadio.setGeometry(QtCore.QRect(80, 130, 51, 17))
        self.priorityLowRadio.setObjectName("priorityLowRadio")
        self.priorityMedRadio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.priorityMedRadio.setGeometry(QtCore.QRect(130, 130, 91, 17))
        self.priorityMedRadio.setObjectName("priorityMedRadio")
        self.priorityHighRadio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.priorityHighRadio.setGeometry(QtCore.QRect(220, 130, 61, 17))
        self.priorityHighRadio.setObjectName("priorityHighRadio")
        self.descriptionLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.descriptionLabel.setGeometry(QtCore.QRect(30, 180, 71, 16))
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.descriptionInput = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.descriptionInput.setGeometry(QtCore.QRect(90, 180, 211, 71))
        self.descriptionInput.setObjectName("descriptionInput")
        self.addButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(310, 320, 75, 23))
        self.addButton.setObjectName("addButton")
        self.exitButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(400, 320, 75, 23))
        self.exitButton.setObjectName("exitButton")
        self.ticketsLabal = QtWidgets.QLabel(parent=self.centralwidget)
        self.ticketsLabal.setGeometry(QtCore.QRect(480, 50, 47, 13))
        self.ticketsLabal.setObjectName("ticketsLabal")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(480, 70, 256, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.statusLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(270, 350, 251, 20))
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titleLabel.setText(_translate("MainWindow", "Help Desk Ticket Tracker"))
        self.ticketIdLabel.setText(_translate("MainWindow", "Ticket ID:"))
        self.userNameLabel.setText(_translate("MainWindow", "User Name:"))
        self.priorityLabel.setText(_translate("MainWindow", "Priority:"))
        self.priorityLowRadio.setText(_translate("MainWindow", "Low"))
        self.priorityMedRadio.setText(_translate("MainWindow", "Medium"))
        self.priorityHighRadio.setText(_translate("MainWindow", "High"))
        self.descriptionLabel.setText(_translate("MainWindow", "Description:"))
        self.addButton.setText(_translate("MainWindow", "Add Ticket"))
        self.exitButton.setText(_translate("MainWindow", "Exit"))
        self.ticketsLabal.setText(_translate("MainWindow", "Tickets:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
